// Généré depuis ISO 3166-1 (i18n-iso-countries). code alpha-2 -> [id numérique ISO (world-atlas), nom FR]
export const COUNTRIES: Record<string, [string, string]> = {
  AD: ["020", "Andorre"],
  AE: ["784", "Émirats Arabes Unis"],
  AF: ["004", "Afghanistan"],
  AG: ["028", "Antigua-et-Barbuda"],
  AI: ["660", "Anguilla"],
  AL: ["008", "Albanie"],
  AM: ["051", "Arménie"],
  AO: ["024", "Angola"],
  AQ: ["010", "Antarctique"],
  AR: ["032", "Argentine"],
  AS: ["016", "Samoa américaines"],
  AT: ["040", "Autriche"],
  AU: ["036", "Australie"],
  AW: ["533", "Aruba"],
  AX: ["248", "Åland"],
  AZ: ["031", "Azerbaïdjan"],
  BA: ["070", "Bosnie-Herzégovine"],
  BB: ["052", "Barbade"],
  BD: ["050", "Bangladesh"],
  BE: ["056", "Belgique"],
  BF: ["854", "Burkina Faso"],
  BG: ["100", "Bulgarie"],
  BH: ["048", "Bahreïn"],
  BI: ["108", "Burundi"],
  BJ: ["204", "Bénin"],
  BL: ["652", "Saint-Barthélemy"],
  BM: ["060", "Bermudes"],
  BN: ["096", "Brunei Darussalam"],
  BO: ["068", "Bolivie"],
  BQ: ["535", "Bonaire, Saint-Eustache et Saba"],
  BR: ["076", "Brésil"],
  BS: ["044", "Bahamas"],
  BT: ["064", "Bhoutan"],
  BV: ["074", "Île Bouvet"],
  BW: ["072", "Botswana"],
  BY: ["112", "Biélorussie"],
  BZ: ["084", "Belize"],
  CA: ["124", "Canada"],
  CC: ["166", "Îles Cocos"],
  CD: ["180", "République démocratique du Congo"],
  CF: ["140", "République Centrafricaine"],
  CG: ["178", "République du Congo"],
  CH: ["756", "Suisse"],
  CI: ["384", "Côte-d'Ivoire"],
  CK: ["184", "Îles Cook"],
  CL: ["152", "Chili"],
  CM: ["120", "Cameroun"],
  CN: ["156", "Chine"],
  CO: ["170", "Colombie"],
  CR: ["188", "Costa Rica"],
  CU: ["192", "Cuba"],
  CV: ["132", "Cap-Vert"],
  CW: ["531", "Curaçao"],
  CX: ["162", "Île Christmas"],
  CY: ["196", "Chypre"],
  CZ: ["203", "République Tchèque"],
  DE: ["276", "Allemagne"],
  DJ: ["262", "Djibouti"],
  DK: ["208", "Danemark"],
  DM: ["212", "Dominique"],
  DO: ["214", "République Dominicaine"],
  DZ: ["012", "Algérie"],
  EC: ["218", "Équateur"],
  EE: ["233", "Estonie"],
  EG: ["818", "Égypte"],
  EH: ["732", "Sahara occidental"],
  ER: ["232", "Érythrée"],
  ES: ["724", "Espagne"],
  ET: ["231", "Éthiopie"],
  FI: ["246", "Finlande"],
  FJ: ["242", "Fidji"],
  FK: ["238", "Îles Malouines"],
  FM: ["583", "Micronésie"],
  FO: ["234", "Îles Féroé"],
  FR: ["250", "France"],
  GA: ["266", "Gabon"],
  GB: ["826", "Royaume-Uni"],
  GD: ["308", "Grenade"],
  GE: ["268", "Géorgie"],
  GF: ["254", "Guyane française"],
  GG: ["831", "Guernesey"],
  GH: ["288", "Ghana"],
  GI: ["292", "Gibraltar"],
  GL: ["304", "Groenland"],
  GM: ["270", "Gambie"],
  GN: ["324", "Guinée"],
  GP: ["312", "Guadeloupe"],
  GQ: ["226", "Guinée équatoriale"],
  GR: ["300", "Grèce"],
  GS: ["239", "Géorgie du Sud-et-les Îles Sandwich du Sud"],
  GT: ["320", "Guatemala"],
  GU: ["316", "Guam"],
  GW: ["624", "Guinée-Bissau"],
  GY: ["328", "Guyana"],
  HK: ["344", "Hong Kong"],
  HM: ["334", "Îles Heard-et-MacDonald"],
  HN: ["340", "Honduras"],
  HR: ["191", "Croatie"],
  HT: ["332", "Haïti"],
  HU: ["348", "Hongrie"],
  ID: ["360", "Indonésie"],
  IE: ["372", "Irlande"],
  IL: ["376", "Israël"],
  IM: ["833", "Île de Man"],
  IN: ["356", "Inde"],
  IO: ["086", "Océan Indien Britannique"],
  IQ: ["368", "Irak"],
  IR: ["364", "Iran"],
  IS: ["352", "Islande"],
  IT: ["380", "Italie"],
  JE: ["832", "Jersey"],
  JM: ["388", "Jamaïque"],
  JO: ["400", "Jordanie"],
  JP: ["392", "Japon"],
  KE: ["404", "Kenya"],
  KG: ["417", "Kirghizistan"],
  KH: ["116", "Cambodge"],
  KI: ["296", "Kiribati"],
  KM: ["174", "Comores"],
  KN: ["659", "Saint-Christophe-et-Niévès"],
  KP: ["408", "Corée du Nord"],
  KR: ["410", "Corée du Sud"],
  KW: ["414", "Koweït"],
  KY: ["136", "Îles Caïmans"],
  KZ: ["398", "Kazakhstan"],
  LA: ["418", "Laos"],
  LB: ["422", "Liban"],
  LC: ["662", "Sainte-Lucie"],
  LI: ["438", "Liechtenstein"],
  LK: ["144", "Sri Lanka"],
  LR: ["430", "Libéria"],
  LS: ["426", "Lesotho"],
  LT: ["440", "Lituanie"],
  LU: ["442", "Luxembourg"],
  LV: ["428", "Lettonie"],
  LY: ["434", "Libye"],
  MA: ["504", "Maroc"],
  MC: ["492", "Monaco"],
  MD: ["498", "Moldavie"],
  ME: ["499", "Monténégro"],
  MF: ["663", "Saint-Martin (partie française)"],
  MG: ["450", "Madagascar"],
  MH: ["584", "Îles Marshall"],
  MK: ["807", "Macédoine du Nord"],
  ML: ["466", "Mali"],
  MM: ["104", "Myanmar"],
  MN: ["496", "Mongolie"],
  MO: ["446", "Macao"],
  MP: ["580", "Îles Mariannes du Nord"],
  MQ: ["474", "Martinique"],
  MR: ["478", "Mauritanie"],
  MS: ["500", "Montserrat"],
  MT: ["470", "Malte"],
  MU: ["480", "Maurice"],
  MV: ["462", "Maldives"],
  MW: ["454", "Malawi"],
  MX: ["484", "Mexique"],
  MY: ["458", "Malaisie"],
  MZ: ["508", "Mozambique"],
  NA: ["516", "Namibie"],
  NC: ["540", "Nouvelle-Calédonie"],
  NE: ["562", "Niger"],
  NF: ["574", "Île Norfolk"],
  NG: ["566", "Nigéria"],
  NI: ["558", "Nicaragua"],
  NL: ["528", "Pays-Bas"],
  NO: ["578", "Norvège"],
  NP: ["524", "Népal"],
  NR: ["520", "Nauru"],
  NU: ["570", "Niué"],
  NZ: ["554", "Nouvelle-Zélande"],
  OM: ["512", "Oman"],
  PA: ["591", "Panama"],
  PE: ["604", "Pérou"],
  PF: ["258", "Polynésie française"],
  PG: ["598", "Papouasie-Nouvelle-Guinée"],
  PH: ["608", "Philippines"],
  PK: ["586", "Pakistan"],
  PL: ["616", "Pologne"],
  PM: ["666", "Saint-Pierre-et-Miquelon"],
  PN: ["612", "Îles Pitcairn"],
  PR: ["630", "Porto Rico"],
  PS: ["275", "Palestine"],
  PT: ["620", "Portugal"],
  PW: ["585", "Palaos"],
  PY: ["600", "Paraguay"],
  QA: ["634", "Qatar"],
  RE: ["638", "Réunion"],
  RO: ["642", "Roumanie"],
  RS: ["688", "Serbie"],
  RU: ["643", "Russie"],
  RW: ["646", "Rwanda"],
  SA: ["682", "Arabie Saoudite"],
  SB: ["090", "Îles Salomon"],
  SC: ["690", "Seychelles"],
  SD: ["729", "Soudan"],
  SE: ["752", "Suède"],
  SG: ["702", "Singapour"],
  SH: ["654", "Sainte-Hélène"],
  SI: ["705", "Slovénie"],
  SJ: ["744", "Svalbard et Île Jan Mayen"],
  SK: ["703", "Slovaquie"],
  SL: ["694", "Sierra Leone"],
  SM: ["674", "Saint-Marin"],
  SN: ["686", "Sénégal"],
  SO: ["706", "Somalie"],
  SR: ["740", "Suriname"],
  SS: ["728", "Soudan du Sud"],
  ST: ["678", "São Tomé-et-Principe"],
  SV: ["222", "El Salvador"],
  SX: ["534", "Saint-Martin (partie néerlandaise)"],
  SY: ["760", "Syrie"],
  SZ: ["748", "Royaume d'Eswatini"],
  TC: ["796", "Îles Turques-et-Caïques"],
  TD: ["148", "Tchad"],
  TF: ["260", "Terres australes françaises"],
  TG: ["768", "Togo"],
  TH: ["764", "Thaïlande"],
  TJ: ["762", "Tadjikistan"],
  TK: ["772", "Tokelau"],
  TL: ["626", "Timor-Leste"],
  TM: ["795", "Turkménistan"],
  TN: ["788", "Tunisie"],
  TO: ["776", "Tonga"],
  TR: ["792", "Turquie"],
  TT: ["780", "Trinité-et-Tobago"],
  TV: ["798", "Tuvalu"],
  TW: ["158", "Taïwan"],
  TZ: ["834", "République unie de Tanzanie"],
  UA: ["804", "Ukraine"],
  UG: ["800", "Ouganda"],
  UM: ["581", "Îles mineures éloignées des États-Unis"],
  US: ["840", "États-Unis d'Amérique"],
  UY: ["858", "Uruguay"],
  UZ: ["860", "Ouzbékistan"],
  VA: ["336", "Saint-Siège (Vatican)"],
  VC: ["670", "Saint-Vincent-et-les-Grenadines"],
  VE: ["862", "Venezuela"],
  VG: ["092", "Îles vierges britanniques"],
  VI: ["850", "Îles vierges américaines"],
  VN: ["704", "Vietnam"],
  VU: ["548", "Vanuatu"],
  WF: ["876", "Wallis-et-Futuna"],
  WS: ["882", "Samoa"],
  XK: ["983", "Kosovo"],
  YE: ["887", "Yémen"],
  YT: ["175", "Mayotte"],
  ZA: ["710", "Afrique du Sud"],
  ZM: ["894", "Zambie"],
  ZW: ["716", "Zimbabwe"],
};

export function getCountryName(alpha2: string | null | undefined): string {
  if (!alpha2) return "Inconnu";
  return COUNTRIES[alpha2.toUpperCase()]?.[1] ?? alpha2;
}

export function getCountryNumericId(alpha2: string | null | undefined): string | null {
  if (!alpha2) return null;
  return COUNTRIES[alpha2.toUpperCase()]?.[0] ?? null;
}
